# Copyright (c) 2014 The renderer Authors. All rights
# reserved. Use of this source code is governed by a BSD-style license that
# can be found in the LICENSE file.


common_sources = '''
  renderer/app.cc
  renderer/handler.cc
  renderer/render_handler.cc
  renderer/request_handler.cc
'''


app_sources = '''
  renderer/main.cc
'''


subprocess_sources = '''
  renderer/subprocess.cc
'''


libs = ['cef', 'cef_dll_wrapper', 'glog', 'gflags']
flags = ['-Werror', '-Wall']
include_paths = ['#src', '/cef']
lib_paths = ['/usr/local/lib', '/cef', '/cef/obj.target']


env = Environment()
env.ParseConfig('pkg-config --cflags --libs gtk+-2.0')
include_paths.append(env['CPPPATH'])


def create_objs(sources):
  return [env.Object(source, CPPPATH=include_paths, CPPFLAGS=flags) for source in Split(sources)]


common_objs = create_objs(common_sources)
app_objs = common_objs + create_objs(app_sources)
subprocess_objs = common_objs + create_objs(subprocess_sources)


env.Program('#bin/renderer', app_objs, LIBS=libs,
    LIBPATH=lib_paths)

env.Program('#bin/subprocess', subprocess_objs, LIBS=libs,
    LIBPATH=lib_paths, CPPFLAGS=flags)
